### ISSUE TITLE
E-ehentai信息抓取失败

### ISSUE THREAD

**Issue by originalMemory** [yingziwu/doujinshi_metadata_plugins#2]
前段时间使用插件获取元数据时总是失败，拿曾经成功过的再试也抓取不了。报错信息如下：
calibre, version 3.16.0
错误： 无匹配项: <p>Failed to find any books that match your search. Try making the search <b>less specific</b>. For example, use only the author's last name and a single distinctive word from the title.<p>To see the full log, click "Show details".

Running identify query with parameters: 
{u'authors': [u'\u30d0\u30b9\u505c\u30b7\u30e3\u30ef\u30fc (\u6842\u4e95\u3088\u3057\u3042\u304d)'], u'timeout': 30, u'title': u'\u6deb\u4e71NUIDE TRIP \uff5esex harem 02\uff5e + \u304a\u307e\u3051\u30af\u30ea\u30a2\u30d5\u30a1\u30a4\u30eb', u'identifiers': {u'ehentai': u'1101067_22a3e9de23_0'}} 
Using plugins: E-hentai Galleries (1, 1, 2) 
The log from individual plugins is below 

****************************** E-hentai Galleries (1, 1, 2) ****************************** 
Found 0 results 
Downloading from E-hentai Galleries took 28.8059999943 
Failed to make identify query: u'https://e-hentai.org/?f_apply=Apply%2BFilter&f_non-h=1&f_doujinshi=1&f_western=1&f_misc=1&advsearch=1&f_artistcg=1&f_search=%E6%B7%AB%E4%B9%B1NUIDE+TRIP+%EF%BD%9Esex+harem+02%EF%BD%9E+%2B+%E3%81%8A%E3%81%BE%E3%81%91%E3%82%AF%E3%83%AA%E3%82%A2%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB+%E3%83%90%E3%82%B9%E5%81%9C%E3%82%B7%E3%83%A3%E3%83%AF%E3%83%BC+%E6%A1%82%E4%BA%95%E3%82%88%E3%81%97%E3%81%82%E3%81%8D&f_imageset=1&f_asianporn=1&f_srdd=2&f_cosplay=1&f_sname=on&f_manga=1&f_gamecg=1&f_sh=on'
Traceback (most recent call last):
  File "calibre_plugins.dummy1.__init__", line 266, in identify
  File "site-packages\mechanize\_mechanize.py", line 239, in open_novisit
  File "site-packages\mechanize\_mechanize.py", line 284, in _mech_open
  File "site-packages\mechanize\_opener.py", line 195, in open
  File "site-packages\mechanize\_urllib2_fork.py", line 352, in _open
  File "site-packages\mechanize\_urllib2_fork.py", line 340, in _call_chain
  File "site-packages\calibre\utils\browser.py", line 28, in https_open
  File "site-packages\mechanize\_urllib2_fork.py", line 1160, in do_open
URLError: <urlopen error [Errno 10060] > 

******************************************************************************** 
The identify phase took 28.87 seconds 
The longest time (28.806000) was taken by: E-hentai Galleries 
Merging results from different sources and finding earliest  publication dates from the worldcat.org service 
We have 0 merged results, merging took: 0.00 seconds

**Comment by troyliu0105** [comment]
emmmm。。。请检查您的网络是否需要代理，我这边对https://api.e-hentai.org/api.php 是不能直接访问的。所以要对calibre设置代理

**Comment by originalMemory** [comment]
我挂代理试了下，可以用了，谢谢
